//
toggleKeys = {
    conj: 1,
    centres: 1,
    lines: 1,
    plane: 1,
    chart: 1,
    colours: 0,
    coords: 0,
    grid: 1,
    chart3d: 0,
    jumps: 0,
    more: 1,
    scale3d: 0,
    summary: 1,
    indexComposer: 1,
    table: 1,
    globalIds: 0,
    globalise: 1,
    palindromicComposites: 0,
    mixedComposites: 0,
    orthogonalComposites: 0,
    associates: 0,
    products: 0,
    productByOrbits: 1,
    productBlankIdentity: 1,
    productCommuteIdentity: 1,
    multi: 0,
    orbitEditor: 0
}