//
toggleKeys = {
    conj: 1,
    centres: 1,
    lines: 1,
    plane: 1,
    chart: 1,
    colours: 0,
    coords: 0,
    grid: 1,
    chart3d: 0,
    jumps: 0,
    //midi: 0,
    more: 0,
    scale3d: 0,
    summary: 1,
    table: 1,
    globalIds: 0,
    composites: 0,
    associates: 0,
    products: 0,
    productByOrbits: 1,
    productBlankIdentity: 1,
    productCommuteIdentity: 1,
    multi: 0,
    editor: 0,
    negpol: 0
}